# Generated by Django 5.0.4 on 2024-05-02 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='avatar',
            new_name='image',
        ),
    ]
