# Generated by Django 6.0.3 on 2026-04-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_message_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subtitulo',
        ),
    ]
